const movies = [
  {
    id: "spiderverse",
    title: "Spider-Man: Un Nuevo Universo",
    year: 2018,
    duration: "1h 51min",
    rating: "PG-13",
    genres: ["Animación", "Acción", "Inspiradora"],
    description:
      "Miles Morales descubre un multiverso donde cualquiera puede ser Spider-Man. Ganadora del Óscar® a Mejor Película Animada.",
    trailerUrl: "assets/sample-trailer.mp4",
    poster: "assets/poster-spiderverse.jpg",
    rentPrice: "MX$50.00",
    buyPrice: "MX$149.00",
  },
  {
    id: "oppenheimer",
    title: "Oppenheimer",
    year: 2023,
    duration: "3h 0min",
    rating: "R",
    genres: ["Drama", "Histórica", "Biográfica"],
    description:
      "La historia de J. Robert Oppenheimer, el físico detrás del Proyecto Manhattan y la bomba atómica.",
    trailerUrl: "assets/sample-trailer.mp4",
    poster: "assets/poster-oppenheimer.jpg",
    rentPrice: "MX$70.00",
    buyPrice: "MX$199.00",
  },
  {
    id: "barbie",
    title: "Barbie",
    year: 2023,
    duration: "1h 54min",
    rating: "PG-13",
    genres: ["Comedia", "Fantasía"],
    description:
      "Barbie vive en Barbieland, un mundo perfecto hasta que una crisis existencial la lleva al mundo real.",
    trailerUrl: "assets/sample-trailer.mp4",
    poster: "assets/poster-barbie.jpg",
    rentPrice: "MX$60.00",
    buyPrice: "MX$179.00",
  },
  {
    id: "johnwick4",
    title: "John Wick 4",
    year: 2023,
    duration: "2h 49min",
    rating: "R",
    genres: ["Acción", "Crimen"],
    description:
      "John Wick descubre un camino para derrotar a la Alta Mesa, pero primero debe enfrentarse a poderosos enemigos.",
    trailerUrl: "assets/sample-trailer.mp4",
    poster: "assets/poster-johnwick4.jpg",
    rentPrice: "MX$70.00",
    buyPrice: "MX$199.00",
  },
  {
    id: "dune2",
    title: "Dune: Parte Dos",
    year: 2024,
    duration: "2h 45min",
    rating: "PG-13",
    genres: ["Ciencia ficción", "Aventura"],
    description:
      "Paul Atreides se une a los Fremen en su camino de venganza contra quienes destruyeron su familia.",
    trailerUrl: "assets/sample-trailer.mp4",
    poster: "assets/poster-dune2.jpg",
    rentPrice: "MX$80.00",
    buyPrice: "MX$220.00",
  },
  {
    id: "guardians3",
    title: "Guardianes de la Galaxia Vol. 3",
    year: 2023,
    duration: "2h 30min",
    rating: "PG-13",
    genres: ["Acción", "Comedia", "Ciencia ficción"],
    description:
      "Peter Quill y su equipo se enfrentan a una nueva amenaza mientras intentan proteger a uno de los suyos.",
    trailerUrl: "assets/sample-trailer.mp4",
    poster: "assets/poster-guardians3.jpg",
    rentPrice: "MX$65.00",
    buyPrice: "MX$189.00",
  },
];
